resources:
  - ../../../base/second-step

namespace: cloudnotes-prod

images:
  - name: cloudnotes-client
    newName: ${DOCKER_USERNAME}/cloudnotes-client
    newTag: latest
    
patches:
  - path: patch-ingress-host.yaml
  - path: patch-image-pull-secret.yaml
