resources:
- ../../../base/second-step

namespace: cloudnotes-local

images:
- name: cloudnotes-client
  newName: cloudnotes-client
  newTag: local-1760863421
- name: cloudnotes-server
  newName: cloudnotes-server
  newTag: ffb6e83
  
patches:
- path: patch-ingress-host.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
