resources:
- ../../../base/second-step
namespace: cloudnotes-local
images:
- name: cloudnotes-client
  newName: cloudnotes-client
  newTag: local-1761041260
- name: cloudnotes-server
  newName: cloudnotes-server
  newTag: local-1761040762
patches:
- path: patch-ingress-host.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
