resources:
- pvc.yaml
- ../../../base/first-step
namespace: cloudnotes-local
images:
- name: cloudnotes-server
  newName: cloudnotes-server
  newTag: local-1761040762
patches:
- path: remove-server-hostpath.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
