resources:
  - pvc.yaml
  - ../../../base/first-step

namespace: cloudnotes-prod

images:
  - name: cloudnotes-server
    
patches:
  - path: remove-server-hostpath.yaml
  - path: patch-image-pull-secret.yaml

