resources:
  - pvc.yaml
  - ../../../base/first-step

namespace: cloudnotes-prod

images:
  - name: cloudnotes-server
    newName: ${DOCKER_USERNAME}/cloudnotes-server
    newTag: latest
    
patches:
  - path: remove-server-hostpath.yaml
  - path: patch-image-pull-secret.yaml

